const AccountTypes = {
    GET_STUDENTACCOUNT_REQUEST: "GET_STUDENTACCOUNT_REQUEST",
    GET_STUDENTACCOUNT_SUCCESS: "GET_STUDENTACCOUNT_SUCCESS",
    GET_STUDENTACCOUNT_FAILURE: "GET_STUDENTACCOUNT_FAILURE",
};

export { AccountTypes };