const CampusAdminTypes = {
  GET_All_COLLEGE_REQUEST: "GET_All_COLLEGE_REQUEST",
  GET_All_COLLEGE_SUCCESS: "GET_All_COLLEGE_SUCCESS",
  GET_All_COLLEGE_FAILURE: "GET_All_COLLEGE_FAILURE",

  // Add College
  ADD_COLLEGE_REQUEST: "ADD_COLLEGE_REQUEST",
  ADD_COLLEGE_SUCCESS: "ADD_COLLEGE_SUCCESS",
  ADD_COLLEGE_FAILURE: "ADD_COLLEGE_FAILURE",

  // Update College
  UPDATE_COLLEGE_REQUEST: "UPDATE_COLLEGE_REQUEST",
  UPDATE_COLLEGE_SUCCESS: "UPDATE_COLLEGE_SUCCESS",
  UPDATE_COLLEGE_FAILURE: "UPDATE_COLLEGE_FAILURE",

  // Add Branding
  ADD_BRANDING_REQUEST: "ADD_BRANDING_REQUEST",
  ADD_BRANDING_SUCCESS: "ADD_BRANDING_SUCCESS",
  ADD_BRANDING_FAILURE: "ADD_BRANDING_FAILURE",

  // On Board College
  ONBOARD_COLLEGE_REQUEST: "ONBOARD_COLLEGE_REQUEST",
  ONBOARD_COLLEGE_SUCCESS: "ONBOARD_COLLEGE_SUCCESS",
  ONBOARD_COLLEGE_FAILURE: "ONBOARD_COLLEGE_FAILURE",
};

export { CampusAdminTypes };
