const CollegeAdminTypes = {
  GET_All_STUDENT_REQUEST: "GET_All_STUDENT_REQUEST",
  GET_All_STUDENT_SUCCESS: "GET_All_STUDENT_SUCCESS",
  GET_All_STUDENT_FAILURE: "GET_All_STUDENT_FAILURE",

  // Grouped Students Upload csv
  GROUP_UPLOAD_STUDENTS_REQUEST: "GROUP_UPLOAD_STUDENTS_REQUEST",
  GROUP_UPLOAD_STUDENTS_SUCCESS: "GROUP_UPLOAD_STUDENTS_SUCCESS",
  GROUP_UPLOAD_STUDENTS_FAILURE: "GROUP_UPLOAD_STUDENTS_FAILURE",
};

export { CollegeAdminTypes };
