const HistoryTypes = {
  GET_HISTORY_REQUEST: "GET_HISTORY_REQUEST",
  GET_HISTORY_SUCCESS: "GET_HISTORY_SUCCESS",
  GET_HISTORY_FAILURE: "GET_HISTORY_FAILURE",

  FILTER_HISTORY_REQUEST: "FILTER_HISTORY_REQUEST",
  FILTER_HISTORY_SUCCESS: "FILTER_HISTORY_SUCCESS",
  FILTER_HISTORY_FAILURE: "FILTER_HISTORY_FAILURE",

  SEARCH_HISTORY_REQUEST: "SEARCH_HISTORY_REQUEST",
  SEARCH_HISTORY_SUCCESS: "SEARCH_HISTORY_SUCCESS",
  SEARCH_HISTORY_FAILURE: "SEARCH_HISTORY_FAILURE",
};

export { HistoryTypes };
