const StatementTypes = {
  GET_STATEMENT_REQUEST: "GET_STATEMENT_REQUEST",
  GET_STATEMENT_SUCCESS: "GET_STATEMENT_SUCCESS",
  GET_STATEMENT_FAILURE: "GET_STATEMENT_FAILURE",
};

export { StatementTypes };
