const StatesTypes = {
  GET_ALL_STATES_REQUEST: "GET_ALL_STATES_REQUEST",
  GET_ALL_STATES_SUCCESS: "GET_ALL_STATES_SUCCESS",
  GET_ALL_STATES_FAILURE: "GET_ALL_STATES_FAILURE",
};

export { StatesTypes };
